import type { AgentManifest, SkillManifest } from '@studio/catalog/types';
import { permissiveLicense, provenance } from '@studio/catalog/validation';

const internalSource = provenance({
  sourceId: 'veldra-core',
  repository: 'local://veldra',
  revision: 'working-tree',
  path: 'studio/catalog/examples/veldra-engineering.ts',
  importedAs: 'internal',
});
const internalLicense = permissiveLicense('MIT', 'Project-owned foundation metadata');

export const veldraEngineeringAgents: AgentManifest[] = [
  {
    kind: 'agent',
    schemaVersion: 1,
    id: 'android-kotlin-specialist',
    name: 'Android Kotlin Specialist',
    description: 'Handles portable mobile and Kotlin implementation tasks.',
    capabilities: ['android', 'kotlin', 'mobile', 'implementation'],
    domains: ['android', 'mobile'],
    languages: ['kotlin'],
    frameworks: ['compose'],
    task_types: ['implementation', 'analysis'],
    required_tools: ['filesystem', 'git', 'testing'],
    compatible_skills: ['android-native', 'testing-strategies'],
    risk_level: 'medium',
    approval_required: false,
    context_requirements: {},
    source: internalSource,
    license: internalLicense,
    enabled: true,
  },
  {
    kind: 'agent',
    schemaVersion: 1,
    id: 'studio-architecture-reviewer',
    name: 'Studio Architecture Reviewer',
    description: 'Reviews portable cross-platform boundaries and architecture changes.',
    capabilities: ['architecture', 'review', 'android'],
    domains: ['architecture', 'android'],
    languages: ['typescript', 'kotlin'],
    frameworks: ['capacitor', 'react'],
    task_types: ['analysis', 'review'],
    required_tools: ['filesystem', 'git', 'testing'],
    compatible_skills: ['architecture-review', 'testing-strategies'],
    risk_level: 'medium',
    approval_required: false,
    context_requirements: {},
    source: internalSource,
    license: internalLicense,
    enabled: true,
  },
  {
    kind: 'agent',
    schemaVersion: 1,
    id: 'security-reviewer',
    name: 'Security Reviewer',
    description: 'Checks security-sensitive implementation and integration changes.',
    capabilities: ['security', 'review', 'mcp'],
    domains: ['security', 'mcp'],
    languages: ['typescript', 'kotlin'],
    frameworks: [],
    task_types: ['analysis', 'review'],
    required_tools: ['filesystem', 'testing'],
    compatible_skills: ['security-review'],
    risk_level: 'high',
    approval_required: true,
    context_requirements: {},
    source: internalSource,
    license: internalLicense,
    enabled: true,
  },
  {
    kind: 'agent',
    schemaVersion: 1,
    id: 'disabled-unrelated-agent',
    name: 'Disabled Unrelated Agent',
    description: 'Fixture proving disabled and irrelevant entries are excluded.',
    capabilities: ['database'],
    domains: ['database'],
    languages: ['sql'],
    frameworks: [],
    task_types: ['implementation'],
    required_tools: [],
    compatible_skills: [],
    risk_level: 'low',
    approval_required: false,
    context_requirements: {},
    source: internalSource,
    license: internalLicense,
    enabled: false,
  },
];

export const veldraEngineeringSkills: SkillManifest[] = [
  {
    kind: 'skill',
    schemaVersion: 1,
    id: 'android-native',
    name: 'Android Native Development',
    description: 'Progressively loads Android-native implementation guidance.',
    triggers: ['android', 'kotlin', 'native'],
    capabilities: ['android', 'kotlin', 'mobile'],
    domains: ['android', 'mobile'],
    dependencies: [],
    conflicts: [],
    risk_level: 'low',
    source: internalSource,
    license: internalLicense,
    enabled: true,
  },
  {
    kind: 'skill',
    schemaVersion: 1,
    id: 'testing-strategies',
    name: 'Testing Strategies',
    description: 'Progressively loads test planning and verification guidance.',
    triggers: ['test', 'testing', 'verification'],
    capabilities: ['testing', 'quality'],
    domains: ['testing'],
    dependencies: [],
    conflicts: [],
    risk_level: 'low',
    source: internalSource,
    license: internalLicense,
    enabled: true,
  },
  {
    kind: 'skill',
    schemaVersion: 1,
    id: 'architecture-review',
    name: 'Architecture Review',
    description: 'Reviews a proposed change against the existing studio boundaries.',
    triggers: ['architecture', 'review'],
    capabilities: ['architecture', 'review'],
    domains: ['architecture'],
    dependencies: ['testing-strategies'],
    conflicts: [],
    risk_level: 'medium',
    source: internalSource,
    license: internalLicense,
    enabled: true,
  },
  {
    kind: 'skill',
    schemaVersion: 1,
    id: 'security-review',
    name: 'Security Review',
    description: 'Checks security boundaries before implementation is executed.',
    triggers: ['security', 'mcp'],
    capabilities: ['security', 'mcp'],
    domains: ['security', 'mcp'],
    dependencies: [],
    conflicts: [],
    risk_level: 'high',
    source: internalSource,
    license: internalLicense,
    enabled: true,
  },
];
